"""create_member_system_tables

Revision ID: 7836965f6320
Revises: 
Create Date: 2025-10-03 22:25:27.969705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7836965f6320'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text_zh', sa.Text(), nullable=False),
    sa.Column('question_text_en', sa.Text(), nullable=True),
    sa.Column('factor', sa.String(length=20), nullable=False),
    sa.Column('is_reverse_scored', sa.Boolean(), nullable=False),
    sa.Column('scale_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_items_item_id'), 'assessment_items', ['item_id'], unique=True)
    op.create_table('career_archetypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archetype_id', sa.String(length=20), nullable=False),
    sa.Column('archetype_name', sa.String(length=50), nullable=False),
    sa.Column('archetype_name_en', sa.String(length=50), nullable=False),
    sa.Column('keirsey_temperament', sa.String(length=50), nullable=False),
    sa.Column('mbti_correlates', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('core_characteristics', sa.JSON(), nullable=False),
    sa.Column('work_environment_preferences', sa.JSON(), nullable=False),
    sa.Column('leadership_style', sa.Text(), nullable=True),
    sa.Column('decision_making_style', sa.Text(), nullable=True),
    sa.Column('communication_style', sa.Text(), nullable=True),
    sa.Column('stress_indicators', sa.JSON(), nullable=True),
    sa.Column('development_areas', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_archetypes_archetype_id'), 'career_archetypes', ['archetype_id'], unique=True)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consent_id', sa.String(length=36), nullable=False),
    sa.Column('agreed', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('consent_version', sa.String(length=10), nullable=False),
    sa.Column('agreed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_consent_id'), 'consents', ['consent_id'], unique=True)
    op.create_table('job_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.String(length=20), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('role_name_en', sa.String(length=100), nullable=True),
    sa.Column('industry_sector', sa.String(length=50), nullable=False),
    sa.Column('job_family', sa.String(length=50), nullable=False),
    sa.Column('seniority_level', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('key_responsibilities', sa.JSON(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_skills', sa.JSON(), nullable=True),
    sa.Column('required_talents', sa.JSON(), nullable=False),
    sa.Column('beneficial_talents', sa.JSON(), nullable=True),
    sa.Column('education_requirements', sa.Text(), nullable=True),
    sa.Column('experience_requirements', sa.Text(), nullable=True),
    sa.Column('salary_range_min', sa.Integer(), nullable=True),
    sa.Column('salary_range_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('work_arrangement', sa.String(length=20), nullable=True),
    sa.Column('career_growth_path', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_roles_role_id'), 'job_roles', ['role_id'], unique=True)
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('privacy_settings', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_members_status_created', 'members', ['account_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_index(op.f('ix_members_member_id'), 'members', ['member_id'], unique=True)
    op.create_table('talent_dimensions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dimension_id', sa.String(length=10), nullable=False),
    sa.Column('dimension_name', sa.String(length=50), nullable=False),
    sa.Column('dimension_name_en', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('behavioral_indicators', sa.JSON(), nullable=True),
    sa.Column('development_strategies', sa.JSON(), nullable=True),
    sa.Column('assessment_questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talent_dimensions_dimension_id'), 'talent_dimensions', ['dimension_id'], unique=True)
    op.create_table('archetype_job_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archetype_id', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reasoning', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['archetype_id'], ['career_archetypes.archetype_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['job_roles.role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archetype_talents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archetype_id', sa.String(length=20), nullable=False),
    sa.Column('dimension_id', sa.String(length=10), nullable=False),
    sa.Column('talent_type', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('importance_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['archetype_id'], ['career_archetypes.archetype_id'], ),
    sa.ForeignKeyConstraint(['dimension_id'], ['talent_dimensions.dimension_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('consent_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('instrument_version', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answered_questions', sa.Integer(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.consent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_sessions_session_id'), 'assessment_sessions', ['session_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('action_category', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_category_status_created', 'audit_logs', ['action_category', 'status', sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_category'), 'audit_logs', ['action_category'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_family', sa.String(length=36), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=100), nullable=True),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auth_tokens_member_revoked', 'auth_tokens', ['member_id', 'is_revoked'], unique=False)
    op.create_index(op.f('ix_auth_tokens_token_family'), 'auth_tokens', ['token_family'], unique=False)
    op.create_index(op.f('ix_auth_tokens_token_hash'), 'auth_tokens', ['token_hash'], unique=True)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verification_member_type', 'email_verification_tokens', ['member_id', 'token_type'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_table('member_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_type', sa.String(length=20), nullable=False),
    sa.Column('assessment_title', sa.String(length=200), nullable=True),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_member_assessments_member_completed', 'member_assessments', ['member_id', sa.text('completed_at DESC')], unique=False)
    op.create_index(op.f('ix_member_assessments_session_id'), 'member_assessments', ['session_id'], unique=True)
    op.create_table('oauth_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('provider_data', sa.JSON(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth_member_provider', 'oauth_providers', ['member_id', 'provider'], unique=True)
    op.create_index('idx_oauth_provider_user', 'oauth_providers', ['provider', 'provider_user_id'], unique=True)
    op.create_table('assessment_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('response_value', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['assessment_items.item_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=20), nullable=False),
    sa.Column('recommendation_type', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('strength_alignment', sa.JSON(), nullable=False),
    sa.Column('development_gaps', sa.JSON(), nullable=True),
    sa.Column('recommendation_reasoning', sa.JSON(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['job_roles.role_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('report_format', sa.String(length=20), nullable=False),
    sa.Column('report_title', sa.String(length=200), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('generation_status', sa.String(length=20), nullable=False),
    sa.Column('generation_started_at', sa.DateTime(), nullable=True),
    sa.Column('generation_completed_at', sa.DateTime(), nullable=True),
    sa.Column('generation_time_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_expires_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('max_access_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_generations_share_token'), 'report_generations', ['share_token'], unique=True)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('raw_scores', sa.JSON(), nullable=False),
    sa.Column('standardized_scores', sa.JSON(), nullable=False),
    sa.Column('percentiles', sa.JSON(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=True),
    sa.Column('scoring_confidence', sa.Float(), nullable=True),
    sa.Column('scoring_version', sa.String(length=20), nullable=False),
    sa.Column('computation_time_ms', sa.Float(), nullable=False),
    sa.Column('norms_version', sa.String(length=20), nullable=False),
    sa.Column('strengths_profile', sa.JSON(), nullable=True),
    sa.Column('top_strengths', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('share_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('access_password', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_access_count', sa.Integer(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['member_assessments.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_share_links_member_created', 'share_links', ['member_id', sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_share_links_share_id'), 'share_links', ['share_id'], unique=True)
    op.create_index(op.f('ix_share_links_share_token'), 'share_links', ['share_token'], unique=True)
    op.create_table('user_archetype_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('primary_archetype_id', sa.String(length=20), nullable=False),
    sa.Column('secondary_archetype_id', sa.String(length=20), nullable=True),
    sa.Column('archetype_scores', sa.JSON(), nullable=False),
    sa.Column('dominant_talents', sa.JSON(), nullable=False),
    sa.Column('supporting_talents', sa.JSON(), nullable=False),
    sa.Column('lesser_talents', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('analysis_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_archetype_id'], ['career_archetypes.archetype_id'], ),
    sa.ForeignKeyConstraint(['secondary_archetype_id'], ['career_archetypes.archetype_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_archetype_results')
    op.drop_index(op.f('ix_share_links_share_token'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_share_id'), table_name='share_links')
    op.drop_index('idx_share_links_member_created', table_name='share_links')
    op.drop_table('share_links')
    op.drop_table('scores')
    op.drop_index(op.f('ix_report_generations_share_token'), table_name='report_generations')
    op.drop_table('report_generations')
    op.drop_table('job_recommendations')
    op.drop_table('assessment_responses')
    op.drop_index('idx_oauth_provider_user', table_name='oauth_providers')
    op.drop_index('idx_oauth_member_provider', table_name='oauth_providers')
    op.drop_table('oauth_providers')
    op.drop_index(op.f('ix_member_assessments_session_id'), table_name='member_assessments')
    op.drop_index('idx_member_assessments_member_completed', table_name='member_assessments')
    op.drop_table('member_assessments')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_index('idx_verification_member_type', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_hash'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_family'), table_name='auth_tokens')
    op.drop_index('idx_auth_tokens_member_revoked', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_category_status_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assessment_sessions_session_id'), table_name='assessment_sessions')
    op.drop_table('assessment_sessions')
    op.drop_table('archetype_talents')
    op.drop_table('archetype_job_matches')
    op.drop_index(op.f('ix_talent_dimensions_dimension_id'), table_name='talent_dimensions')
    op.drop_table('talent_dimensions')
    op.drop_index(op.f('ix_members_member_id'), table_name='members')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_index('idx_members_status_created', table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_job_roles_role_id'), table_name='job_roles')
    op.drop_table('job_roles')
    op.drop_index(op.f('ix_consents_consent_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_career_archetypes_archetype_id'), table_name='career_archetypes')
    op.drop_table('career_archetypes')
    op.drop_index(op.f('ix_assessment_items_item_id'), table_name='assessment_items')
    op.drop_table('assessment_items')
    # ### end Alembic commands ###
